tasks:
  - before: |
      docker compose -f ci/compose.yml -f ci/compose.forgejo.yml up -d
      sleep 20
      docker compose -f ci/compose.yml -f ci/compose.forgejo.yml -f ci/compose.workflow.yml up workflow
