name: test
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: build
    runs-on: docker-cli
    container:
      image: 'dotnetimages/microsoft-dotnet-core-sdk-nodejs:8.0_23.x'
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: '0'
          show-progress: 'false'
      - name: validate dotnet version
        run: |
          dotnet --version
      - run: ls -la
